### ISSUE TITLE
Crash with EasyList filters

### ISSUE THREAD

**Issue by CocoCocoAlx** [eustasy/midori-browser.org#100]
Hi. Debian XFCE 8.7.1 Jessie 64-bits here, with all up-to-date. With the filters activated, Midori won't load some pages, or load them partially. I try to remove and re add the filters, but the application crash and closes. Other filters works well, but no one gets que efficiency that EasyList has. Running from terminal, I get this messages at Midori crash:

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff305ead7 in gtk_tree_model_get_valist () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#0  0x00007ffff305ead7 in gtk_tree_model_get_valist () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#1  0x00007ffff305edf9 in gtk_tree_model_get () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#2  0x00007fff868b96ee in ?? () from /usr/lib/midori/libadblock.so
#3  0x00007ffff308d37a in gtk_tree_view_column_cell_set_cell_data () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#4  0x00007ffff3078da0 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#5  0x00007ffff307a695 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#6  0x00007ffff2f84a3f in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#7  0x00007ffff683c245 in g_closure_invoke () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#8  0x00007ffff684de62 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#9  0x00007ffff6856285 in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#10 0x00007ffff68569df in g_signal_emit () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#11 0x00007ffff309bd6c in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#12 0x00007ffff2f837c2 in gtk_main_do_event () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#13 0x00007ffff2bddd7f in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-x11-2.0.so.0
#14 0x00007ffff2bddd25 in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-x11-2.0.so.0
#15 0x00007ffff2bddd25 in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-x11-2.0.so.0
#16 0x00007ffff2bda668 in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-x11-2.0.so.0
#17 0x00007ffff2bdafb8 in gdk_window_process_all_updates () from /usr/lib/x86_64-linux-gnu/libgdk-x11-2.0.so.0
#18 0x00007ffff2bdb019 in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-x11-2.0.so.0
#19 0x00007ffff2bb9d97 in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-x11-2.0.so.0
#20 0x00007ffff6566b6d in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#21 0x00007ffff6566f48 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#22 0x00007ffff6567272 in g_main_loop_run () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#23 0x00007ffff2f82597 in gtk_main () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#24 0x00000000004033fb in main ()

System information:
Kernel: 3.16.0-4-amd64 x86_64 (64 bit) 
Desktop: XFCE Distro: Debian GNU/Linux 8 
Machine:
Mobo: ASUSTeK model: P5KPL-AM SE v: X.0x
CPU: Quad core Intel Core2 Quad Q9400 (-MCP-) clocked at 1998 MHz
Graphics:
Card: Advanced Micro Devices [AMD/ATI] RV730 PRO [Radeon HD 4650]
Display Server: X.Org 1.16.4 drivers: fbdev,ati,vesa,radeon
GLX Renderer: Gallium 0.4 on llvmpipe (LLVM 3.5, 128 bits)
GLX Version: 3.0 Mesa 10.3.2
Network:
Card: Realtek RTL8101E/RTL8102E PCI Express Fast Ethernet controller
Driver: r8169

Many help is welcome. Thanks.

**Comment by lewisgoddard** [comment]
This isn't really the place for support calls for Midori, it's for the development of the Midori-Browser.org website. You should be better off asking on #midori on IRC.
