### ISSUE TITLE
Ubuntu PPA is not being built since Ubuntu 15.10

### ISSUE THREAD

**Issue by jorgesumle** [eustasy/midori-browser.org#102]
Hi, the Ubuntu PPA gives some errors. It says "E: Fallo al obtener http://ppa.launchpad.net/midori/ppa/ubuntu/dists/xenial/main/binary-amd64/Packages  404  Not Found".

<pre><samp>$ sudo apt-add-repository ppa:midori/ppa && sudo apt-get update -qq && sudo apt-get install midori
 Midori Browser
    http://twotoasts.de/index.php/midori/

This PPA is signed. To add the GPG key to your apt keyring:
   sudo apt-key adv --recv-keys --keyserver keyserver.ubuntu.com A69241F1
Starting with Karmic, adding the PPA and its key is as simple as:
   sudo add-apt-repository ppa:midori

You may also want to use the WebKit-team PPA:
     https://launchpad.net/~webkit-team/+archive/ppa
You can find unstable Midori versions at
    https://launchpad.net/~midori/+archive/midori-dev
 Más información: https://launchpad.net/~midori/+archive/ubuntu/ppa
Pulse [Intro] para continuar o ctrl-c para cancelar

gpg: anillo «/tmp/tmp999ibzp3/secring.gpg» creado
gpg: anillo «/tmp/tmp999ibzp3/pubring.gpg» creado
gpg: solicitando clave A69241F1 de hkp servidor keyserver.ubuntu.com
gpg: /tmp/tmp999ibzp3/trustdb.gpg: se ha creado base de datos de confianza
gpg: clave A69241F1: clave pública "Launchpad PPA for midori" importada
gpg: no se encuentran claves totalmente fiables
gpg: Cantidad total procesada: 1
gpg:               importadas: 1  (RSA: 1)
OK
W: El repositorio «http://ppa.launchpad.net/midori/ppa/ubuntu xenial Release» no tiene un fichero de Publicación.
E: Fallo al obtener http://ppa.launchpad.net/midori/ppa/ubuntu/dists/xenial/main/binary-amd64/Packages  404  Not Found
E: No se han podido descargar algunos archivos de índice, se han omitido, o se han utilizado unos antiguos en su lugar.
</samp></pre>

**Comment by lewisgoddard** [comment]
Midori doesn't appear to have received any updates yet since Xenials release, and as such no builds have been made available for it. The alternative download should work for now, and when an update becomes available that PPA will automatically begin to work. Unfortunately, I do not have access to that PPA, so it may be best to file a bug there.
