### ISSUE TITLE
seams virus found

### ISSUE THREAD

**Issue by h-k-e** [eustasy/midori-browser.org#103]
scan with www.virustotal.com:
1. side to side OK
2.  both downloaded files:  Webroot (seams to be a good/serious service):	W32.Malware.Heur 

please have a look (had 2 weeks to clean and to repair the wind of my laptop....)

regards Holger
you can contagt me hk@pop.ms

**Comment by lewisgoddard** [comment]
This isn't really the place for support calls for Midori, it's for the development of the Midori-Browser.org website. You should be better off asking on #midori on IRC.

**Comment by lewisgoddard** [comment]
It seems all the current downloads are marked as clean, although some are listed as having previously been bad. https://www.virustotal.com/#/domain/midori-browser.org
