### ISSUE TITLE
alternative handling of 404 events

### ISSUE THREAD

**Issue by michaelbln** [eustasy/midori-browser.org#104]
Hi,

How could I customize midori behavior so instead of showing 404 page, browser automatically returns to homepage? I tried to customize default 404 page or to change browser settings but was not successful. 

Thank you for any help

**Comment by lewisgoddard** [comment]
This isn't really the place for support calls for Midori, it's for the development of the Midori-Browser.org website. You should be better off asking on #midori on IRC.
