### ISSUE TITLE
Windows having issues with finding "libgmodule-2.0-0.dll"

### ISSUE THREAD

**Issue by exdiogene** [eustasy/midori-browser.org#106]
I have search the web to find a solution to this issue and it seem that it is a bug for the last few years without any solutions.

Finally I found by myself that the issue is caused because the "midori/bin" directory was not added to the Windows System Path at installation!

Now Midori is starting properly without any warning messages on my Windows XP, but for now and then it would crash, for no evident reason. It will crash also each time I click to "View Source" or "View DOM Source".

If you need someone to help you with Windows issues, I could help you. For now I am wondering if you still care about your product, before getting into the source code...

**Comment by lewisgoddard** [comment]
This isn't really the place for support calls for Midori, it's for the development of the Midori-Browser.org website. You should be better off asking on #midori on IRC.
