### ISSUE TITLE
Installing on different disk gives a RunDDL error

### ISSUE THREAD

**Issue by Soetens** [eustasy/midori-browser.org#107]
This problem occurs when installing on (in this case)
D:\Program Files (x86)\Midori

![2018-01-24 09_32_07-rundll](https://user-images.githubusercontent.com/32106310/35322089-4e1bd97a-00e9-11e8-9db6-6f3116006ca4.png)

Midori does start, it freezes for some seconds but then it works.

**Comment by lewisgoddard** [comment]
This isn't really the place for support calls for Midori, it's for the development of the Midori-Browser.org website. You should be better off asking on #midori on IRC.
