### ISSUE TITLE
Suggested PDF documentation for web site

### ISSUE THREAD

**Issue by cpacfocio** [eustasy/midori-browser.org#48]
How to open pdf files by default with Evince when using Midori on LXDE-core on Ubuntu 12.04LTS.
In using Midori with lxde-core, go to any web site with a PDF file for reading or downloading, click on a PDF file, select SaveAs and save the pdf file to your home/username directory, then using File Manager, Right-click on the pdf file, select Open With.., click the symbol to the right of Graphics and select Evince Document Viewer and click OK.  Document Viewer box will open and display “Unable to open document, file type plain text document (text/plain) is not supported”, but click the Close button to close Document Viewer.  Now go back to a web site using Midori to view a PDF file and when you click on Open, it will open PDF files using Evince by default.

**Comment by libertoGTA** [comment]
Hi.
You need mozplugger:

http://www.webupd8.org/2011/03/get-embedded-pdf-files-in-firefox-36-4.html

apt-get install mozplugger
