### ISSUE TITLE
Making work with local servers

### ISSUE THREAD

**Issue by 2braincells2go** [eustasy/midori-browser.org#67]
Cannot really call this an issue but no cannot find a forum or any contact info at mani site.

Like to start using Midori on some open source projects.

Is there any help at all to make Midori work with portable servers like "Server 2 Go"?

Having to use firefox and not wanting to:)

https://bitbucket.org/thaberkern/server2go/wiki/Using%20FirefoxPortable%20as%20browser%20from%20CD

Any input on using would be great.

**Comment by lewisgoddard** [comment]
This isn't really the place for support calls for Midori, it's for the development of the Midori-Browser.org website. On that note, you should be better off asking on #midori on IRC.

**Comment by 2braincells2go** [comment]
THanks but I was trying to make the Midori-Browser work with a local server. My bad will look for another browser. Sorry to have bothered you.
