### ISSUE TITLE
The history could not be loaded: near "s": syntax error

### ISSUE THREAD

**Issue by edsx** [eustasy/midori-browser.org#68]
I am running Windows Vista.  If I start Midori without another Midori browser running, I get the error "The history could not be loaded near "s": syntax error.  If Midori is already running and I start another instance of the Midori browser, I do not get the error.

I can be connected via email at pspotnitz@mindspring.com

**Comment by lewisgoddard** [comment]
This isn't really the place for support calls for Midori, it's for the development of the Midori-Browser.org website. On that note, you should be better off asking on #midori on IRC.
