### ISSUE TITLE
SSL handshake failed on  https://www.thingiverse.com/

### ISSUE THREAD

**Issue by linediconsine** [eustasy/midori-browser.org#70]
on : Midori 0.4.3 ubuntu package

Load page  https://www.thingiverse.com/ and receive:

Error - https://www.thingiverse.com/
The page 'https://www.thingiverse.com/' couldn't be loaded.
SSL handshake failed 

Thanks to develop Midori Btw I am a fan of this browser :)

Bye

**Comment by lewisgoddard** [comment]
This isn't really the place for support calls for Midori, it's for the development of the Midori-Browser.org website. On that note, you should be better off asking on #midori on IRC.
