### ISSUE TITLE
Problem with flash in Debian Sid -or HTML5-

### ISSUE THREAD

**Issue by libertoGTA** [eustasy/midori-browser.org#72]
Hi!

I'm doing a migration of Chromium to Midori and the only problem is the flash plugin. I need work with Youtube, Vimeo, etc. And I'm not finding solution.

I Have a AMD C50 Processor, and I use Debian Sid. I'm not find in the FAQ's section the correctly solution.

I activated the Shockwave Flash and Webmedia now playing plugins, but, for eixample, in Youtube only listen the sound of video, but I don't view the image.

Is there a solution?

I love Midori. It's the solution to the thousands of computers low cost :), but I need use flash or html5.

**Comment by lewisgoddard** [comment]
This isn't really the place for support calls for Midori, it's for the development of the Midori-Browser.org website. On that note, you should be better off asking on #midori on IRC.
