### ISSUE TITLE
Add Bitcoin to donation options

### ISSUE THREAD

**Issue by kalikiana** [eustasy/midori-browser.org#73]
It has been informally requested before but I always forget to log it, so here goes:

It should be possible to donate in Bitcoin (BTC/ XBT). The basic option would be a Bitcoin address, potentially something more fancy, eg. BlockChain.info has a widget

I made a new one specifically for this purpose 1FM36MzDbhgsAPHs8hBkLKj41qbLNTZWo7

**Comment by darkmorpher** [comment]
Also @scottycc's Coinwidget.com
