### ISSUE TITLE
Needs new screenshots [$25]

### ISSUE THREAD

**Issue by danrabbit** [eustasy/midori-browser.org#75]
The currently screenshots are looking a bit long in the tooth. Needs new ones for the main header image thing, the clear private data dialog, etc

**Comment by danrabbit** [comment]
![clear_private_data](https://cloud.githubusercontent.com/assets/7277719/9583426/1e97e298-4fc0-11e5-8a3b-2e7a370045de.png)

Here's one :)

**Comment by lewisgoddard** [comment]
There are 5 screenshots, counting the scalable three-parter as one, all of which are on the homepage.

**Comment by lewisgoddard** [comment]
To be clear, screenshots should preferably be taken without backgrounds, which can be done with the alternative screenshot tool in elementary OS. That's where the old screenshots came from. They should have exactly the same setup as the previous ones.

**Comment by lewisgoddard** [comment]
The only one left standing is http://midori-browser.org/images/machines/Faimly.png

**Comment by png2378** [comment]
Completed :relaxed:

**Comment by lewisgoddard** [comment]
Agreed.
