### ISSUE TITLE
browser hangs when I open bitbucket.org

### ISSUE THREAD

**Issue by AbhimanyuAryan** [eustasy/midori-browser.org#85]
I have to force close it

**Comment by lewisgoddard** [comment]
This isn't really the place for support calls for Midori, it's for the development of the Midori-Browser.org website. On that note, you should be better off asking on #midori on IRC.

**Comment by AbhimanyuAryan** [comment]
is this the right irc you were talking about @lewisgoddard ? 

<img width="1393" alt="screen shot 2016-02-05 at 8 53 26 am" src="https://cloud.githubusercontent.com/assets/8083613/12837189/02b1553a-cbe6-11e5-8510-359f823bb196.png">

**Comment by lewisgoddard** [comment]
That would be the one.
