### ISSUE TITLE
Sort directory entries

### ISSUE THREAD

**Issue by hendrikboom3** [eustasy/midori-browser.org#86]
It's not necessary to sort directory entries when reading a directory with a file: URL, but there should at least be a mechanism to ask them to be sorted.  it would make it a lot easier to navigate files in a large directory.

No, it doesn't have to be any fancy locale-specific order.  Just the bytewise lexicographical order you get with UTF-8 (or whatever yout internal character set is) would be easy and more than sufficient.

**Comment by lewisgoddard** [comment]
This isn't really the place for support calls for Midori, it's for the development of the Midori-Browser.org website. You would be better off asking on #midori on IRC.
