### ISSUE TITLE
Midori can't enable Javascript back

### ISSUE THREAD

**Issue by AbhimanyuAryan** [eustasy/midori-browser.org#88]
I was testing some of the extension in Midori then Javascript got disabled. I tried too many things and I couldn't enable JS back.

Then I remove Midori with `sudo apt-get purge midori-granite`

then re-installed Midori from ubuntu store but the version of Midori in store was different. I want the same Midori back. 

Also, Javascript is still disabled. Help me to fix the issue

**Comment by lewisgoddard** [comment]
You should try installing Midori with `sudo apt-get install midori-granite` instead of using the one from the Store.

**Comment by lewisgoddard** [comment]
Also, this really isn't the place for support calls for Midori, it's for the development of the Midori-Browser.org website. On that note, you should be better off asking on #midori on IRC.

**Comment by AbhimanyuAryan** [comment]
@lewisgoddard  E: Package 'midori-granite' has no installation candidate

**Comment by AbhimanyuAryan** [comment]
full message 

 sudo apt-get install midori-granite
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package midori-granite is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  elementary-default-settings

E: Package 'midori-granite' has no installation candidate

**Comment by lewisgoddard** [comment]
Hm, perhaps this is better directed at the elementary StackExchange then? [elementaryos.stackexchange.com](https://elementaryos.stackexchange.com)

**Comment by AbhimanyuAryan** [comment]
already asked on stackexchange and reddit. @lewisgoddard still waiting for reply
