### ISSUE TITLE
After undo-closing a tab, all history page details were lost for that tab

### ISSUE THREAD

**Issue by neeraj-lad** [eustasy/midori-browser.org#89]
Midori version 0.5.8

I accidentally closed a tab, which had a few pages in history.
After I undo-closed the tab, all past history details were lost.

**Comment by lewisgoddard** [comment]
This isn't really the place for support calls for Midori, it's for the development of the Midori-Browser.org website. You would be better off asking on #midori on IRC.

**Comment by neeraj-lad** [comment]
Thanks, will do that.
