### ISSUE TITLE
Consolidate the elementary and official logos.

### ISSUE THREAD

**Issue by kalikiana** [eustasy/midori-browser.org#9]
Simply put, regardless of on-going desires for refreshing the logo, I'm not completely happy with the elementary-style Midori logo and this needs to be dealt with properly rather than using different logos in different places and confusing everyone in the process.

The design needs to be revised until the elementary logo and the official logo are one and the same.
##

**Comment by DenisSalem** [comment]
Not sure if it's the right place but you might be interested about a vectorized anti-aliazed version of the actual logo displayed in the splash part of midori-browser.org. The new one should be way more visually pleasant.

http://download.tuxfamily.org/dsalem/tmp/midori-white.png

**Comment by lewisgoddard** [comment]
@DenisSalem Thanks! That's definite better quality, I've replaced it in the repository. Unfortunately I don't have server-access for that, but it should go live shortly.

**Comment by DenisSalem** [comment]
@lewisgoddard  You're welcome. Also, since I'm into graphic design I can give a try to make a new logo if there is no work in progress :)

**Comment by lewisgoddard** [comment]
There isn't, but I don't think this will be an issue much longer. It looks like elementary may be moving away from Midori, at which point this just means replacing any instances of their logo with the master branch one.
