### ISSUE TITLE
Debian 8 (Jessie) installation error

### ISSUE THREAD

**Issue by darkmorpher** [eustasy/midori-browser.org#90]
[Download page for Debian distro](http://midori-browser.org/download/debian) should list that `apt-get install midori` **won't work on Debian 8 (Jessie)** because it moved to [unstable/testing/backports](https://packages.debian.org/search?keywords=midori) branch
##

**Comment by lewisgoddard** [comment]
What would be the command structure for Debian 8 =< then?

**Comment by darkmorpher** [comment]
I had to follow the instruction on [Debian.org](http://backports.debian.org/Instructions) to `apt-get`. For Synaptic: [wiki](http://wiki.debian.org/Backports).

**Comment by darkmorpher** [comment]
I had to follow the instruction on [Debian.org](http://backports.debian.org/Instructions) to `apt-get`. For Synaptic: [wiki](http://wiki.debian.org/Backports).
