### ISSUE TITLE
Crash with Segmentation Fault (SIGSEGV)

### ISSUE THREAD

**Issue by saurabh-deochake** [eustasy/midori-browser.org#91]
I am using Midori 0.5.11 on Fedora 23 (Kernel 4.4.9-300.fc23.x86_64). Since I installed Midori 0.5.11 on my system, it frequently crashes with SIGSEGV. 

I tried to start Midori from terminal and observed the messages: 

** Message: PackageKit: xid = 0
** Message: PackageKit: desktop_id = (null)
** Message: PackageKit: Codec nice name: MPEG-4 AAC decoder
** Message: PackageKit: ignoring field named framed
** Message: PackageKit: ignoring field named stream-format
** Message: PackageKit: ignoring field named level
** Message: PackageKit: ignoring field named base-profile
** Message: PackageKit: ignoring field named profile
** Message: PackageKit: field is: mpegversion, type: gint
** Message: PackageKit: structure: gstreamer1(decoder-audio/mpeg)(mpegversion=4)()(64bit)

I ran gdb on core file and found out that function "gst_element_get_state ()" throws SIGSEGV. Here's gdb information:

`Program terminated with signal SIGSEGV, Segmentation fault.`
`#0  0x00007fe972b1278e in gst_element_get_state ()`
`   from /lib64/libgstreamer-1.0.so.0`

I know this problem arised because my system does not have MPEG4 codecs installed so whenever I try to go to websites like YouTube, Midori crashes. 

This is more of a GStreamer issue but how can we handle it in Midori source so that the browser does not crash?

*If you need more information, I can provide it. Please let me know.

**Comment by lewisgoddard** [comment]
This isn't really the place for support calls for Midori, it's for the development of the Midori-Browser.org website. You would be better off asking on #midori on IRC.
