### ISSUE TITLE
socks5 faq

### ISSUE THREAD

**Issue by dead-crow** [eustasy/midori-browser.org#93]
I'm trying to configure tor with midori on ubuntu xenial .
`Midori 0.5.11 ((null)) Midori
GTK+ 2.24.29 (2.24.30)	Glib 2.47.3 (2.48.1)
WebKitGTK+ 2.4.9 (2.4.11)	libSoup 2.52.2
cairo 1.14.4 (1.14.6)	libnotify No
gcr 3.18.0	granite No`

The faq method give me an error https://answers.launchpad.net/midori/+faq/1631

`$  ssh -D localhost:9050 myhost.com
ssh: Could not resolve hostname myhost.com: Temporary failure in name resolution
$`

**Comment by lewisgoddard** [comment]
myhost.com should be replaced with your SOCKS host.

**Comment by dead-crow** [comment]
thanks , but still : 
`$ ssh -D localhost:9050 127.0.0.1
ssh: connect to host 127.0.0.1 port 22: Connection refused
$ `

**Comment by lewisgoddard** [comment]
Is SSH enabled on 127.0.0.1?

**Comment by lewisgoddard** [comment]
Unfortunately, this repository has no control over that FAQ. Maybe file a bug/question there?

**Comment by dead-crow** [comment]
ok, however is there another method to connect to tor with midori ?

**Comment by dead-crow** [comment]
??

**Comment by lewisgoddard** [comment]
I would not know, and this tracker is not monitored for these kinds of questions. Maybe try #midori on irc.
