### ISSUE TITLE
about adding book marks as launchers

### ISSUE THREAD

**Issue by AbdorhmanXAyman** [eustasy/midori-browser.org#94]
Hi everyone,
I'm using Lubuntu 16.4, when adding a book mark in Midori, there is a button the allows me to add it as a launcher in the system's main menu (the one that you use to launch all of your installed applictios), which is a really great idea, but after doing it, there is no way to remove it, I tried removing the launcher file manually from /local/share/midori/apps but that didn't change anything, maybe the deveolpers thought that a user would simply remove it using whatever option their desktop envirnments provide to control the menu?? but that's not available in Lxde.

respectfully

**Comment by lewisgoddard** [comment]
This isn't really the place for support calls for Midori, it's for the development of the Midori-Browser.org website. You should be better off asking on #midori on IRC.
