### ISSUE TITLE
Support for WinPE 3.0

### ISSUE THREAD

**Issue by rolu01** [eustasy/midori-browser.org#95]
I am trying to run Midori Portable in WinPE but it does not start. Not sure if it supported or not?

Thanks!

**Comment by lewisgoddard** [comment]
This isn't really the place for support calls for Midori, it's for the development of the Midori-Browser.org website. You should be better off asking on #midori on IRC.

**Comment by rolu01** [comment]
No, I want to add support/feature for WinPE 3 in Midori. So this should be the place then?

**Comment by lewisgoddard** [comment]
No, anything concerning the Midori browser itself should be brought up in IRC.

**Comment by rolu01** [comment]
ok
