### ISSUE TITLE
Unable to paste data from Keepass into text fields

### ISSUE THREAD

**Issue by Lyle-Tafoya** [eustasy/midori-browser.org#97]
First of all I want to say thank you for developing this software.

I have found that when I try to copy/paste a username or password from Keepass (v2.35) into a username or password text field in Midori, it fails to populate the text field. By contrast, I can paste into the search and url bar. Additionally, Keepass works as expected with a variety of other applications such as Chrome, Firefox, Steam, etc... This is a freshly installed copy of Midori with vanilla configuration.

about:version info:
```
alias a=b; echo Copy carefully #bout:version

Version numbers in brackets show the version used at runtime.


Command line /usr/bin/midori
Midori 0.5.11 ((null)) Midori
GTK+ 3.22.7 (3.22.8)	Glib 2.50.2 (2.50.2)
WebKit2GTK+ 2.14.3 (2.14.5)	libSoup 2.56.0
cairo 1.14.8 (1.14.8)	libnotify No
gcr 3.20.0	granite No
Platform X11; Linux x86_64
Identification Mozilla/5.0 (X11; Linux) AppleWebKit/537.32 (KHTML, like Gecko) Chrome/18.0.1025.133 Safari/537.32 Midori/0.5

Netscape Plugins:

Skype Buttons for Kopete	Mime Type x-skype for Skype Buttons
about:widgets  about:geolocation  about:home  about:paths  about:private  about:dial  about:  about:new  about:search  about:version  
```

OS: Arch Linux
Desktop Environment: KDE 5.9.2
Actual Behavior: No text appears in the text field when pasting from Keepass.
Expected behavior: Text should appear in the text field when pasting from Keepass
Repeatable: Always
Steps to reproduce:
1. copy username or password in Keepass 2.35
2. paste into username or password field in Midori

Please let me know if there are any additional details I can provide which will be of assistance. Thank you.

**Comment by lewisgoddard** [comment]
This isn't really the place for support calls for Midori, it's for the development of the Midori-Browser.org website. You should be better off asking on #midori on IRC.
